package(default_visibility = ["//visibility:public"])

cc_library(
    name = "userinfo-lib",
    srcs = ["userinfo-server.cc"],
    hdrs = ["userinfo-server.h"],
)

cc_binary(
    name = "userinfo-bin",
    srcs = ["userinfo-server.cc"],   
)